---
language: python
python: "2.7"

dist: trusty

env:
  global:
    - ANSIBLE_ROLES_PATH=tests/roles
    - ANSIBLE_REQUIREMENTS=tests/roles/requirements.yml
  matrix:
    - ANSIBLE_PLAYBOOK=tests/playbooks/git.yml
    - ANSIBLE_PLAYBOOK=tests/playbooks/deb.yml

install:
  - sudo make deps-ansible
  - pip install pyyaml jinja2
  - make ansible

script:
  # Bootstrap Drumkit
  - ". d"

  # Run playbook tests
  - make ansible-playbook-test

  # Check if drush is installed and working.
  - sudo -u aegir -H drush @hm status | grep eldir

